[update_manager klipper-check-mcu]
type: git_repo
path: ~/klipper-check-mcu
origin: https://github.com/joseto1298/klipper-check-mcu.git
managed_services: klipper
primary_branch: main
install_script: setup.sh
